### ISSUE TITLE
Using of the tool

### ISSUE THREAD

**Issue by designpixel** [jonpecar/qrCodeImageSorter#37]
Hi all, I have issues with using the tool. I have installed all the details and parts. But when I try to execute

  python -m qr_image_indexer

the error

 /usr/bin/python: No module named qr_image_indexer

is comming up.

I'm using a debian environment as basesystem. Can you please push me in the right direction where to find a detailled description how to use the tooling?

Thanks
Christian

**Comment by jonpecar** [comment]
I have updated the ReadMe. The instructions were out of date. The command should have been python -m qrImageIndexer.

There is no more detailed documentation than the readme at this time. Please consider using the GUI version, which does have more detailed documentation and includes a how-to video. The process is the same as for this version, but through a GUI. Please see the GUI version [here](https://github.com/jonpecar/qrCodeImageSorterGUI)

**Comment by designpixel** [comment]
Hi Jonpecar, thank you ver much for the answer. Much aprechiated. :)
Can you please give me a hint how to use the tool on mac os? When I start it, the window content and all the buttons are white... I had it one that they are blue and I could see something. But after this once in a time, never happen again. Maybe you have an idea...

Thanks,
Christian

**Comment by designpixel** [comment]
Already done. It is the current version of zbar installed.

**Comment by designpixel** [comment]
Let us move to the GUI thread... ;)

**Comment by designpixel** [comment]
Just as hint - I have moved the topic to the GUI Thread. ;)
